"""add is_autocanceled

Revision ID: 095369069dfe
Revises: 2591cd0b1be8
Create Date: 2022-06-15 00:06:26.378223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095369069dfe'
down_revision = '2591cd0b1be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('is_autocanceled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missions', 'is_autocanceled')
    # ### end Alembic commands ###
