"""add sop_link for device

Revision ID: 0bc92997b835
Revises: 889911adee02
Create Date: 2022-03-22 17:50:42.978309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc92997b835'
down_revision = '889911adee02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('sop_link', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'sop_link')
    # ### end Alembic commands ###
