"""modify user primary key to username

Revision ID: 1a9e6cc9f878
Revises: fa4ef60db66f
Create Date: 2022-03-13 18:39:14.941518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "1a9e6cc9f878"
down_revision = "fa4ef60db66f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_auditlogheaders_users_id_user", "auditlogheaders", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_auditlogheaders_users_username_user",
        "auditlogheaders",
        "users",
        ["user"],
        ["username"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_missions_users_users_user_id", "missions_users", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_missions_users_users_user_username",
        "missions_users",
        "users",
        ["user"],
        ["username"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_userdevicelevels_users_id_user", "userdevicelevels", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_userdevicelevels_users_username_user",
        "userdevicelevels",
        "users",
        ["user"],
        ["username"],
        ondelete="CASCADE",
    )
    op.drop_index("ix_users_id", table_name="users")
    op.drop_constraint("fk_users_users_id_superior", "users", type_="foreignkey")
    op.create_foreign_key(
        "fk_users_users_username_superior", "users", "users", ["superior"], ["username"]
    )
    op.drop_constraint(
        "fk_usershiftinfos_users_id_user", "usershiftinfos", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_usershiftinfos_users_username_user",
        "usershiftinfos",
        "users",
        ["user"],
        ["username"],
    )
    op.drop_constraint(
        "fk_worker_status_users_id_worker", "worker_status", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_worker_status_users_username_worker",
        "worker_status",
        "users",
        ["worker"],
        ["username"],
        ondelete="CASCADE",
    )
    op.drop_column("users", "id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("id", mysql.VARCHAR(length=36), nullable=False))
    op.create_index("ix_users_id", "users", ["id"], unique=False)
    op.drop_constraint(
        "fk_worker_status_users_username_worker", "worker_status", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_worker_status_users_id_worker",
        "worker_status",
        "users",
        ["worker"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_usershiftinfos_users_username_user", "usershiftinfos", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_usershiftinfos_users_id_user", "usershiftinfos", "users", ["user"], ["id"]
    )
    op.drop_constraint("fk_users_users_username_superior", "users", type_="foreignkey")
    op.create_foreign_key(
        "fk_users_users_id_superior", "users", "users", ["superior"], ["id"]
    )
    op.drop_constraint(
        "fk_userdevicelevels_users_username_user",
        "userdevicelevels",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_userdevicelevels_users_id_user",
        "userdevicelevels",
        "users",
        ["user"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_missions_users_users_user_username", "missions_users", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_missions_users_users_user_id",
        "missions_users",
        "users",
        ["user"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_auditlogheaders_users_username_user", "auditlogheaders", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_auditlogheaders_users_id_user",
        "auditlogheaders",
        "users",
        ["user"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
