"""add worker_status's updated_date column

Revision ID: 221d3ffdea41
Revises: 962cd169c651
Create Date: 2022-02-20 21:36:48.530272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "221d3ffdea41"
down_revision = "962cd169c651"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "worker_status",
        sa.Column(
            "updated_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("worker_status", "updated_date")
    # ### end Alembic commands ###
