"""add is_emergency in mission

Revision ID: 229891bc5e99
Revises: c60b2675d08c
Create Date: 2022-02-24 02:41:03.304722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229891bc5e99'
down_revision = 'c60b2675d08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('is_emergency', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missions', 'is_emergency')
    # ### end Alembic commands ###
