"""add whitelist device

Revision ID: 289866c27ff8
Revises: 4047b8cfcd39
Create Date: 2022-06-23 01:31:27.063057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289866c27ff8'
down_revision = '4047b8cfcd39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whitelistdevices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device'], ['devices.id'], name='fk_whitelistdevices_devices_id_device', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device')
    )
    op.create_table('whitelistdevices_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('whitelistdevice', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.username'], name='fk_whitelistdevices_users_users_user_username', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['whitelistdevice'], ['whitelistdevices.id'], name='fk_whitelistdevices_users_whitelistdevices_whitelistdevice_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whitelistdevices_users')
    op.drop_table('whitelistdevices')
    # ### end Alembic commands ###
