"""remove unused properties for mission

Revision ID: 2a2f77e6b2e4
Revises: b1f242730736
Create Date: 2022-03-22 01:00:40.695338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a2f77e6b2e4'
down_revision = 'b1f242730736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missions', 'signature')
    op.drop_column('missions', 'canceled_reason')
    op.drop_column('missions', 'cause_of_issue')
    op.drop_column('missions', 'machine_status')
    op.drop_column('missions', 'image')
    op.drop_column('missions', 'issue_solution')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('issue_solution', mysql.VARCHAR(length=512), nullable=True))
    op.add_column('missions', sa.Column('image', mysql.MEDIUMBLOB(), nullable=True))
    op.add_column('missions', sa.Column('machine_status', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('missions', sa.Column('cause_of_issue', mysql.VARCHAR(length=512), nullable=True))
    op.add_column('missions', sa.Column('canceled_reason', mysql.VARCHAR(length=512), nullable=True))
    op.add_column('missions', sa.Column('signature', mysql.MEDIUMBLOB(), nullable=True))
    # ### end Alembic commands ###
