"""update audit log

Revision ID: 3562261990d0
Revises: b184d7971641
Create Date: 2021-12-29 21:02:30.361110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3562261990d0'
down_revision = 'b184d7971641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_logs_affected_object_key', table_name='logs')
    op.drop_index('ix_logs_category', table_name='logs')
    op.drop_index('ix_logs_id', table_name='logs')
    op.drop_index('ix_logs_related_object_key', table_name='logs')
    op.drop_table('logs')
    op.drop_index('ix_logvaluess_id', table_name='logvaluess')
    op.drop_table('logvaluess')
    op.drop_index('ix_auditlogvaluess_id', table_name='auditlogvaluess')
    op.drop_table('auditlogvaluess')
    op.drop_table('auditlogheaders_logvaluess')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlogheaders_logvaluess',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('logvalues', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('auditlogheader', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['auditlogheader'], ['auditlogheaders.id'], name='fk_auditlogheaders_logvaluess_auditlogheaders_auditlogheader_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['logvalues'], ['logvaluess.id'], name='fk_auditlogheaders_logvaluess_logvaluess_logvalues_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('auditlogvaluess',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('field_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('previous_value', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('new_value', mysql.VARCHAR(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_auditlogvaluess_id', 'auditlogvaluess', ['id'], unique=False)
    op.create_table('logvaluess',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('field_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('previous_value', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('new_value', mysql.VARCHAR(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_logvaluess_id', 'logvaluess', ['id'], unique=False)
    op.create_table('logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('content', mysql.JSON(), nullable=True),
    sa.Column('affected_object_key', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('related_object_key', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_logs_related_object_key', 'logs', ['related_object_key'], unique=False)
    op.create_index('ix_logs_id', 'logs', ['id'], unique=False)
    op.create_index('ix_logs_category', 'logs', ['category'], unique=False)
    op.create_index('ix_logs_affected_object_key', 'logs', ['affected_object_key'], unique=False)
    # ### end Alembic commands ###
