"""update

Revision ID: 38dc412ec5eb
Revises: d1c6270ca171
Create Date: 2022-12-10 07:59:28.960298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38dc412ec5eb'
down_revision = 'd1c6270ca171'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_log_headers_user'), 'audit_log_headers', ['user'], unique=False)
    op.drop_constraint('fk_audit_log_headers_users_badge_user', 'audit_log_headers', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_audit_log_headers_users_badge_user', 'audit_log_headers', 'users', ['user'], ['badge'], ondelete='SET NULL')
    op.drop_index(op.f('ix_audit_log_headers_user'), table_name='audit_log_headers')
    # ### end Alembic commands ###
