"""update missionevent constraints

Revision ID: 4047b8cfcd39
Revises: 6d1a20b6f020
Create Date: 2022-06-20 23:41:52.961640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4047b8cfcd39'
down_revision = '6d1a20b6f020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uc_missionevents_event_id_table_name', table_name='missionevents')
    op.create_unique_constraint('uc_missionevents_event_id_table_name_mission', 'missionevents', ['event_id', 'table_name', 'mission'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_missionevents_event_id_table_name_mission', 'missionevents', type_='unique')
    op.create_index('uc_missionevents_event_id_table_name', 'missionevents', ['event_id', 'table_name'], unique=False)
    # ### end Alembic commands ###
