"""alter mission table

Revision ID: 517f5b424909
Revises: 
Create Date: 2021-09-06 15:31:12.907774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517f5b424909'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
