"""add is_changepwd for user

Revision ID: 889911adee02
Revises: 2a2f77e6b2e4
Create Date: 2022-03-22 01:39:14.039834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889911adee02'
down_revision = '2a2f77e6b2e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_changepwd', sa.Boolean(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_changepwd')
    # ### end Alembic commands ###
