"""add worker status enum

Revision ID: 9520129333da
Revises: 4d0a0117748b
Create Date: 2022-02-23 18:44:56.645852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = "9520129333da"
down_revision = "962cd169c651"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "worker_status", sa.Column("status", sa.String(length=15), nullable=False)
    )
    op.alter_column(
        "auditlogheaders",
        "record_pk",
        existing_type=mysql.VARCHAR(length=100),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "auditlogheaders",
        "record_pk",
        existing_type=mysql.VARCHAR(length=100),
        nullable=False,
    )
    op.drop_column("worker_status", "status")
    # ### end Alembic commands ###
