"""update 1224

Revision ID: a5c93cd2ab86
Revises: 
Create Date: 2021-12-24 14:44:55.520091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c93cd2ab86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('workshop', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_devices_factorymaps_id_workshop', 'devices', 'factorymaps', ['workshop'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_devices_factorymaps_id_workshop', 'devices', type_='foreignkey')
    op.drop_column('devices', 'workshop')
    # ### end Alembic commands ###
