"""test5

Revision ID: b0f0e92b3bf0
Revises: 3fe5654c9c07
Create Date: 2022-11-23 16:04:25.335093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0f0e92b3bf0'
down_revision = '3fe5654c9c07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'shift',
               existing_type=mysql.SMALLINT(),
               nullable=True)
    op.alter_column('users', 'change_pwd',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'change_pwd',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'shift',
               existing_type=mysql.SMALLINT(),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
