"""remove unnecessary constraints

Revision ID: b27ff6a1dce6
Revises: 229891bc5e99
Create Date: 2022-02-24 23:05:43.157459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "b27ff6a1dce6"
down_revision = "229891bc5e99"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categorypris_devices",
        sa.Column("device", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "categorypris_devices", sa.Column("categorypri", sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        "fk_categorypris_devices_devices_category_id",
        "categorypris_devices",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_categorypris_devices_categorypris_devices_id",
        "categorypris_devices",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_categorypris_devices_devices_device_id",
        "categorypris_devices",
        "devices",
        ["device"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_categorypris_devices_categorypris_categorypri_id",
        "categorypris_devices",
        "categorypris",
        ["categorypri"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("categorypris_devices", "devices")
    op.drop_column("categorypris_devices", "category")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categorypris_devices",
        sa.Column("category", mysql.VARCHAR(length=100), nullable=True),
    )
    op.add_column(
        "categorypris_devices",
        sa.Column("devices", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        "fk_categorypris_devices_categorypris_categorypri_id",
        "categorypris_devices",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_categorypris_devices_devices_device_id",
        "categorypris_devices",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_categorypris_devices_categorypris_devices_id",
        "categorypris_devices",
        "categorypris",
        ["devices"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_categorypris_devices_devices_category_id",
        "categorypris_devices",
        "devices",
        ["category"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("categorypris_devices", "categorypri")
    op.drop_column("categorypris_devices", "device")
    # ### end Alembic commands ###
