"""edit whitelist device

Revision ID: b47fb2d7cddc
Revises: 289866c27ff8
Create Date: 2022-06-23 14:58:09.126766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b47fb2d7cddc'
down_revision = '289866c27ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whitelistdevices', 'device',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
    op.create_unique_constraint('uc_whitelistdevices_users', 'whitelistdevices_users', ['user', 'whitelistdevice'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whitelistdevices', 'device',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
    op.drop_constraint('uc_whitelistdevices_users', 'whitelistdevices_users', type_='unique')
