"""remove unique key from mission

Revision ID: c460568d51af
Revises: f12e073109f0
Create Date: 2021-11-29 22:08:57.008781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c460568d51af'
down_revision = 'f12e073109f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='missions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'missions', ['name'], unique=False)
    # ### end Alembic commands ###
