"""1129

Revision ID: c4734ecad4dd
Revises: 517f5b424909
Create Date: 2021-11-29 21:02:07.658457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4734ecad4dd'
down_revision = '517f5b424909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('related_event_id', sa.Integer(), nullable=False))
    op.add_column('repairhistorys', sa.Column('image', sa.LargeBinary(length=5242880), nullable=False))
    op.add_column('repairhistorys', sa.Column('signature', sa.LargeBinary(length=5242880), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repairhistorys', 'signature')
    op.drop_column('repairhistorys', 'image')
    op.drop_column('missions', 'related_event_id')
    # ### end Alembic commands ###
