"""modify shift schema

Revision ID: c55d0dfb418f
Revises: e584a8f46282
Create Date: 2022-03-13 02:42:28.852141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c55d0dfb418f"
down_revision = "e584a8f46282"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deviceinfo_supervisors")
    op.drop_table("deviceinfo_managers")
    op.drop_table("deviceinfo_chiefs")
    op.drop_table("devicemanageinfos")
    op.add_column("users", sa.Column("superior", sa.String(length=36), nullable=True))
    op.add_column(
        "users", sa.Column("shift", sa.Integer(), server_default="0", nullable=True)
    )
    op.create_foreign_key(
        "fk_users_users_id_superior", "users", "users", ["superior"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_users_users_id_superior", "users", type_="foreignkey")
    op.drop_column("users", "shift")
    op.drop_column("users", "superior")
    op.create_table(
        "devicemanageinfos",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("device", mysql.VARCHAR(length=100), nullable=True),
        sa.Column("date", sa.DATE(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device"], ["devices.id"], name="fk_devicemanageinfos_devices_id_device"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "deviceinfo_chiefs",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user", mysql.VARCHAR(length=36), nullable=True),
        sa.Column(
            "devicemanageinfo", mysql.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["devicemanageinfo"],
            ["devicemanageinfos.id"],
            name="fk_deviceinfo_chiefs_devicemanageinfos_devicemanageinfo_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user"],
            ["users.id"],
            name="fk_deviceinfo_chiefs_users_user_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "deviceinfo_managers",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user", mysql.VARCHAR(length=36), nullable=True),
        sa.Column(
            "devicemanageinfo", mysql.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["devicemanageinfo"],
            ["devicemanageinfos.id"],
            name="fk_deviceinfo_managers_devicemanageinfos_devicemanageinfo_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user"],
            ["users.id"],
            name="fk_deviceinfo_managers_users_user_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "deviceinfo_supervisors",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user", mysql.VARCHAR(length=36), nullable=True),
        sa.Column(
            "devicemanageinfo", mysql.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["devicemanageinfo"],
            ["devicemanageinfos.id"],
            name="fk_deviceinfo_supervisors_devicemanageinfos_devicemanageinfo_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user"],
            ["users.id"],
            name="fk_deviceinfo_supervisors_users_user_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
