"""set workerstatus's at_device nullable

Revision ID: cbb771a98db5
Revises: 7a083fb4f7c2
Create Date: 2022-05-12 20:38:32.919119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb771a98db5'
down_revision = '7a083fb4f7c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_worker_status_devices_id_at_device', 'worker_status', type_='foreignkey')
    op.create_foreign_key('fk_worker_status_devices_id_at_device', 'worker_status', 'devices', ['at_device'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_worker_status_devices_id_at_device', 'worker_status', type_='foreignkey')
    op.create_foreign_key('fk_worker_status_devices_id_at_device', 'worker_status', 'devices', ['at_device'], ['id'])
    # ### end Alembic commands ###
