"""seperate events from mission

Revision ID: cd96b3de09f5
Revises: 44a4e87f6dac
Create Date: 2022-04-23 01:57:47.923208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd96b3de09f5'
down_revision = '44a4e87f6dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missionevents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=100), nullable=True),
    sa.Column('done_verified', sa.Boolean(), nullable=True),
    sa.Column('event_start_date', sa.DateTime(), nullable=True),
    sa.Column('event_end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mission'], ['missions.id'], name='fk_missionevents_missions_id_mission', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'table_name', name='uc_missionevents_event_id_table_name')
    )
    op.drop_column('missions', 'done_verified')
    op.drop_column('missions', 'related_event_id')
    op.drop_column('missions', 'event_start_date')
    op.drop_column('missions', 'category')
    op.drop_column('missions', 'event_end_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('event_end_date', mysql.DATETIME(), nullable=True))
    op.add_column('missions', sa.Column('category', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('missions', sa.Column('event_start_date', mysql.DATETIME(), nullable=True))
    op.add_column('missions', sa.Column('related_event_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('missions', sa.Column('done_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_table('missionevents')
    # ### end Alembic commands ###
