"""insert current_UUID column to users table

Revision ID: df73de6f903f
Revises: b47fb2d7cddc
Create Date: 2022-11-14 13:26:22.927178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df73de6f903f'
down_revision = 'b47fb2d7cddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_UUID', sa.String(30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_UUID')
    # ### end Alembic commands ###
