"""create composite unique constraints for missions_users

Revision ID: e584a8f46282
Revises: fc146ef9be4e
Create Date: 2022-03-07 16:49:10.927630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "e584a8f46282"
down_revision = "fc146ef9be4e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "missions_users_UN", "missions_users", ["user", "mission"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("missions_users_UN", "missions_users", type_="unique")
    # ### end Alembic commands ###
