"""made some changes

Revision ID: ed138cc1225c
Revises: 
Create Date: 2021-07-02 00:51:33.321088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed138cc1225c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('missions', 'start_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('missions', 'end_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('missions', 'end_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('missions', 'start_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
