"""add rescue

Revision ID: edadcf309d2b
Revises: a5c93cd2ab86
Create Date: 2021-12-24 15:13:38.480615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'edadcf309d2b'
down_revision = 'a5c93cd2ab86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('is_rescue', sa.Boolean(), nullable=True))
    op.alter_column('devices', 'process',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('devices', 'line',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'line',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('devices', 'process',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('devices', 'is_rescue')
    # ### end Alembic commands ###
