"""update device schema

Revision ID: f12e073109f0
Revises: c4734ecad4dd
Create Date: 2021-11-29 21:14:43.759154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f12e073109f0'
down_revision = 'c4734ecad4dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('project', sa.String(length=50), nullable=False))
    op.add_column('devices', sa.Column('device_name', sa.String(length=20), nullable=False))
    op.drop_column('devices', 'process')
    op.drop_column('devices', 'device')
    op.drop_column('devices', 'machine')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('machine', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('devices', sa.Column('device', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('devices', sa.Column('process', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('devices', 'device_name')
    op.drop_column('devices', 'project')
    # ### end Alembic commands ###
