"""modify user foriegn key on delete

Revision ID: fa4ef60db66f
Revises: c55d0dfb418f
Create Date: 2022-03-13 02:53:56.403141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fa4ef60db66f"
down_revision = "c55d0dfb418f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_auditlogheaders_users_id_user", "auditlogheaders", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_auditlogheaders_users_id_user",
        "auditlogheaders",
        "users",
        ["user"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_userdevicelevels_users_id_user", "userdevicelevels", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_userdevicelevels_users_id_user",
        "userdevicelevels",
        "users",
        ["user"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "fk_worker_status_users_id_worker", "worker_status", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_worker_status_users_id_worker",
        "worker_status",
        "users",
        ["worker"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_worker_status_users_id_worker", "worker_status", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_worker_status_users_id_worker", "worker_status", "users", ["worker"], ["id"]
    )
    op.drop_constraint(
        "fk_userdevicelevels_users_id_user", "userdevicelevels", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_userdevicelevels_users_id_user",
        "userdevicelevels",
        "users",
        ["user"],
        ["id"],
    )
    op.drop_constraint(
        "fk_auditlogheaders_users_id_user", "auditlogheaders", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_auditlogheaders_users_id_user", "auditlogheaders", "users", ["user"], ["id"]
    )
    # ### end Alembic commands ###
