"""add category in mission

Revision ID: fc146ef9be4e
Revises: 914c5ca81f80
Create Date: 2022-03-07 03:13:07.710784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc146ef9be4e'
down_revision = '914c5ca81f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('category', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missions', 'category')
    # ### end Alembic commands ###
